// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmEgeulLM-j_ARIW4lZkF9yLNxkUs0HB8',
    appId: '1:669294062001:android:b543e7165840d2b2a27590',
    messagingSenderId: '669294062001',
    projectId: 'wingmanapp-a8de3',
    storageBucket: 'wingmanapp-a8de3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnjiYYRSdcwj_l_hKb0yoHk0Yjj65V1ug',
    appId: '1:669294062001:ios:1927512899332d58a27590',
    messagingSenderId: '669294062001',
    projectId: 'wingmanapp-a8de3',
    storageBucket: 'wingmanapp-a8de3.firebasestorage.app',
    iosClientId: '669294062001-i8jnjtmn6b8ki4qqddkgb003uuuq295r.apps.googleusercontent.com',
    iosBundleId: 'com.example.wingmanApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzqFR9Ia-8H1M-fxaJ49EDld3aghn-6ps',
    appId: '1:669294062001:web:4bd3a0139c48782fa27590',
    messagingSenderId: '669294062001',
    projectId: 'wingmanapp-a8de3',
    authDomain: 'wingmanapp-a8de3.firebaseapp.com',
    storageBucket: 'wingmanapp-a8de3.firebasestorage.app',
    measurementId: 'G-PGCP2LP1LG',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnjiYYRSdcwj_l_hKb0yoHk0Yjj65V1ug',
    appId: '1:669294062001:ios:1927512899332d58a27590',
    messagingSenderId: '669294062001',
    projectId: 'wingmanapp-a8de3',
    storageBucket: 'wingmanapp-a8de3.firebasestorage.app',
    iosClientId: '669294062001-i8jnjtmn6b8ki4qqddkgb003uuuq295r.apps.googleusercontent.com',
    iosBundleId: 'com.example.wingmanApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzqFR9Ia-8H1M-fxaJ49EDld3aghn-6ps',
    appId: '1:669294062001:web:627a378c2a66e553a27590',
    messagingSenderId: '669294062001',
    projectId: 'wingmanapp-a8de3',
    authDomain: 'wingmanapp-a8de3.firebaseapp.com',
    storageBucket: 'wingmanapp-a8de3.firebasestorage.app',
    measurementId: 'G-14NBXK8KGH',
  );

}